### ISSUE TITLE
기존 URI (/userReview) 대문자 -> 소문자

### ISSUE THREAD

**Issue by 97kim** [97kim/mytrip#55]
프론트엔드 ajax 부분이랑 백엔드 Controller에 있는 URI(/userReview 관련)를 수정해야 할 것 같습니다.

하이픈(-)을 사용할까요?
ex) /user-review

아니면 소문자로 할까요?
ex) /userreview 

`제 생각으로는 가독성을 높이기 위해 하이픈이 적절할 거 같습니다.`

**Comment by hyojin-dev** [comment]
스프링 여러 예제들 살펴보니 하이픈 형태로 보이는 것은 찾아보질 못해서 소문자가 좋을 것 같습니다.

**Comment by 97kim** [comment]
해당 부분은 의견이 나뉘어서 튜터님께 피드백 받아보면 좋을 거 같아요 !

**Comment by 97kim** [comment]
review로 수정입니다!!
