### ISSUE TITLE
부하 테스트 지표 남기기

### ISSUE THREAD

**Issue by 97kim** [97kim/mytrip#66]
튜터님이 보내주신 서버_부하_테스트.pdf 참고하면서 시도하면 좋을 것 같습니다.

**Comment by 97kim** [comment]
nGrinder를 사용해
용량이 큰 이미지를 업로드 하면 느려지는 현상에 대해 부하 테스트 진행 후 개선하는 방향으로 나아가보면 좋을 것 같습니다.

**Comment by hyojin-dev** [comment]
넵 확인했습니다!
