### ISSUE TITLE
피드백 정리

### ISSUE THREAD

**Issue by 97kim** [97kim/mytrip#68]
- API 설계가 RESTful 하게 설계가 되었는지 고민할 것 + 디테일 하게 작성 (내가 만약 동료 개발자라면 이 문서를 보고 작업을 할 수 있도록)
ex) https://docs.github.com/en/rest/reference/actions
- 사용한 기술에 대해서는 팀원들이 다 알고 있어야 함
- ERD 설계에도 타입이 명시 되어야 보기 좋음
- 금요일까지 남은 작업들 우선 순위 정해볼 것
- 리팩토링이라는 것은 코드 레벨에서만 언급되는 것이 아닌 API 설계, ERD, 아키텍처, 인프라... 등 넓게 볼 수 있음

**Comment by 97kim** [comment]
제가 이해한 내용 적어보았습니다

**Comment by woogys** [comment]
제가 정리한 부분도 적습니다. 경중님과 중복되는 내용도 있을 수 있습니다.

* ERD에 타입 명시 필요(Vachar, Long etc) (인텔리제이에서 DB띄워서 타입 어떻게 되어 있는지 확인 가능)
* RestAPI 개념 다시 확인하고 representational, resource, method 같은 키워드 연관해서 생각해보기
* API request, response 부분 누가 봐도(ex: 동료 개발자, 프론트엔드 엔지니어) 이해할 수 있게 작성해야 함. 어떤 형식으로 써야 하는지는 카카오, 네이버 API 등 참고해서 보완할 것
* PUT, POST, PATCH, GET 차이점들 명확히 이해하고 사용
* rest doc 공식 문서들은 실시간 수업 시간에 시트에 소개한 레퍼런스들 참고, 활용
* API 구성 중 "weather" 부분 검토 필요 (포인트가 명명의 문제인지 아니면 같은 api가 theme, nearspot 두 가지로 나뉘어 있는 비효율의 문제인지는 모르겠음)
* as is(현재) / to be (미래) 식으로 나누어서 분석 프로세스를 해봐도 좋을 것(?)
* API는 지금 당장 자동화가 어려우면 WIKI에서 우선 버전 관리 진행하고 프로젝트 이후에 시도할 수도 있음
* API는 일단 수정하고 튜터님 피드백 이후에 코드에 반영하는 것이 들이는 품을 줄일 수 있을 것임
* "우리가 잘한 것 자랑"의 예시: 사용한 기술이 무엇인지, 그 기술 외에는 어떤 다른 방식이 있는지, 그럼에도 불구하고 그 기술을 사용한 이유는 무엇인지, 선택해서 얻은 이점이나 장점은 무엇인지 등의 흐름으로 설명할 수 있음

**Comment by hyojin-dev** [comment]
리팩토링 진행 중입니다!
