### ISSUE TITLE
카카오톡 공유하기 관련 사항

### ISSUE THREAD

**Issue by 97kim** [97kim/mytrip#85]
이전에는 인덱스 페이지에서 한국관광공사 API로 여행지 데이터를 불러올 때
근처, 인기 여행지 상세 데이터를 세션 스토리지에 넣어 그 데이터들을 상세페이지에 출력했었습니다.

최근에 여행지 소개 문구를 추가하려고 상세 페이지에 나오는 정보들도 한국관광공사 API에 요청을 하는 거로 바꿨습니다.

그래서 근처, 인기 여행지 상세 페이지에도 카카오톡 공유하기 기능을 넣을 수 있을 것 같다는 생각이 들었습니다.

발표까지 시간이 얼마 남지 않았으니 발표 끝나고 구현해보는 거 어떨까요??

**Comment by hyojin-dev** [comment]
넵 좋을 것 같습니다
