### ISSUE TITLE
input 창에 script문 넣으면 적용되는 XSS 이슈 발견

### ISSUE THREAD

**Issue by 97kim** [97kim/mytrip#86]
![](https://images.velog.io/images/rudwnd33/post/bfd0d88e-50a9-4f89-848b-518b11b48411/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202021-12-14%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%202.34.10.png)

위처럼 작성 시

![](https://images.velog.io/images/rudwnd33/post/3ca121e0-bff6-4609-82bc-5897be5b6213/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202021-12-14%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%202.34.58.png)

- script문이 아주 잘 작동합니다. `XSS` 이슈 해결해야 할 것 같습니다.

**Comment by woogys** [comment]
XSS prevention이 필요하겠네요 확인했습니다
