### ISSUE TITLE
사용자 피드백 정리

### ISSUE THREAD

**Issue by woogys** [97kim/mytrip#87]
### **좋았던 기능**
-코로나 감염자 4 
-주변 여행지 13
-리뷰 1
-즐겨찾기 3
-날씨 1

### **별로였던 기능**
-인터페이스 2 - 분류, 게시물 숫자 보이는 UI등 
-리뷰 2 - 추천 여행지/주변 여행지에서 바로 볼 수 있었으면 좋겠다
-팝업 1 - 로그인 되었다는 팝업 필요?
-로그인 2 - 소셜 로그인 없어 아쉬움 / 여행지 사이트에 로그인이 무슨 필요? / 정보 입력 후 엔터를 쳐도 바로 로그인 되었으면 좋겠음
-주변 여행지 1 - 여행지 소개가 너무 간략함 (관광공사 API 활용의 문제점인듯)
-개구리 사진 - 대체 필요
-즐겨찾기
-메뉴 세분화 미흡(카테고리 UI 불명확)
-추천 여행지 볼 게 별로 없음
-상세 페이지
-지도 : 길찾기 연동 제안

### **추가되면 좋을 것 같은 기능**
-지도에 간략한 여행지 핀 (위치 변경해서 보고 싶다는 의견도)
-여행 루트에 대한 소개
-평점, 랭킹 시스템
-걷기좋은 코스, 근처 호텔, 계절별 여행지, 실사용 리뷰, 인증 사진 업로드(리뷰가 아니라 체크인 개념인듯)
-검색기능 추가 - QueryDSL을 사용한다면 동적쿼리를 사용한 검색기능을 구현하고, 
게시물 숫자를 가져오는 UI와 함께 페이지 하단이나 상단에 제공.
-길찾기
-여행지 상세 페이지 자체에 리뷰 기능
-관광지 정보(전화번호, 오픈시간, 입장료 등)
-사진 많이 많이!
-숙박 예약이나 네이버 다음 지도로 연결

### **버그나 문제점**
-안드로이드 폰에서 theme이 보이지 않을 떄가 있다는 의견
-내 주변 여행지 로딩 속도 느림
-사파리로 접속시 위치 허용해도 nearspot이 잘 안뜸
-url에 html이나 id값이 노출되는 부분은 수정하는 것이 좋을 것 같음 
-팝업메시지를 JS의 기본 alert말고 모달을 이용하면 더 트렌디한 구성이 아닐까 함

**Comment by 97kim** [comment]
정리해주셔서 보기 편하네요 감사합니다!! 유저 피드백에 대해 이야기를 해야겠군요

**Comment by hyojin-dev** [comment]
개선할 부분이 많네요!
